spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:file:${workspace.path}/application;COMPRESS=true"
    username: chartsy
    password: chartsy
  h2:
    console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none